# =============================================================
#  interview_service.py  –  Interview Feedback Microservice
#  (FastAPI, Oracle-backed)
#  Run on its own port, e.g.  python interview_service.py
#  The Flask app (frontend/app.py) is a plain HTTP proxy in front
#  of this service — it does not touch Oracle or business logic
#  directly, matching app.py's other microservice proxy routes.
# =============================================================

import os
import pathlib
import statistics
from collections import defaultdict
from typing import Optional

from contextlib import asynccontextmanager

import oracledb
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# ------------------------------------------------------------------
# ENV LOADING  (same .env convention as app.py / clientcollabration.py)
# ------------------------------------------------------------------
_script_dir = pathlib.Path(__file__).resolve().parent
for _candidate in [
    _script_dir / ".env",
    _script_dir / ".env.txt",
    pathlib.Path.cwd() / ".env",
    pathlib.Path.cwd() / ".env.txt",
]:
    if _candidate.exists():
        load_dotenv(dotenv_path=_candidate, override=True)
        print(f"[interview_service] dotenv loaded: {_candidate}")
        break

# ------------------------------------------------------------------
# ORACLE CONFIG  (same host/user/password fallback convention as app.py)
# ------------------------------------------------------------------
ORACLE_HOST         = os.getenv("ORACLE_HOST", "56.228.73.210")
ORACLE_PORT         = int(os.getenv("ORACLE_PORT", "1521"))
ORACLE_SERVICE_NAME = os.getenv("ORACLE_SERVICE_NAME", "FREEPDB1")
ORACLE_USER         = os.getenv("ORACLE_USER", "SUPPORT")
ORACLE_PASSWORD     = os.getenv("ORACLE_PASSWORD", "Welcome123")


def get_connection():
    dsn = oracledb.makedsn(ORACLE_HOST, ORACLE_PORT, service_name=ORACLE_SERVICE_NAME)
    conn = oracledb.connect(user=ORACLE_USER, password=ORACLE_PASSWORD, dsn=dsn)

    cur = conn.cursor()
    cur.execute("ALTER SESSION SET CURRENT_SCHEMA = CHAKORA")
    cur.close()

    return conn


# ------------------------------------------------------------------
# SCHEMA  (idempotent create — works whether or not the table exists)
#
# This matches the LIVE table (confirmed via DESC interview_feedback):
# round1_* / round2_* per-round scorecards, not a single shared
# technical/problem-solving/communication/culture set.
#
# NOTE: on the table as it exists today, the four ROUND1_* columns
# below are NOT NULL. That's fine for a "1st Round" submission, but
# a "2nd Round" (or any non-round-1) submission — where the form
# disables the round-1 inputs and only posts round2_* fields — will
# try to insert NULL into those NOT NULL columns and fail with an
# Oracle constraint error. If you're seeing inserts fail on Round 2+
# feedback, run this once against the existing table:
#
#   ALTER TABLE interview_feedback MODIFY (
#       round1_communication_soft_skills          NUMBER(1) NULL,
#       round1_basic_technical_skill_assessment    NUMBER(1) NULL,
#       round1_project_explanation                 NUMBER(1) NULL,
#       round1_logical_ability                     NUMBER(1) NULL
#   );
#
# The CREATE_TABLE_SQL below already creates these nullable, so a
# fresh table (or a fresh environment) won't hit this.
# ------------------------------------------------------------------
CREATE_TABLE_SQL = """
CREATE TABLE interview_feedback (
    id                                          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_name                              VARCHAR2(200) NOT NULL,
    position                                    VARCHAR2(200) NOT NULL,
    interview_round                             VARCHAR2(100) NOT NULL,
    interviewer_name                            VARCHAR2(200) NOT NULL,
    interview_date                              VARCHAR2(20)  NOT NULL,
    round1_communication_soft_skills            NUMBER(1),
    round1_basic_technical_skill_assessment      NUMBER(1),
    round1_project_explanation                  NUMBER(1),
    round1_logical_ability                      NUMBER(1),
    round1_resume                               NUMBER(1),
    round2_introduction                         NUMBER(1),
    round2_general_programming                  NUMBER(1),
    round2_python_basics                        NUMBER(1),
    round2_python_advanced                      NUMBER(1),
    round2_oops                                 NUMBER(1),
    round2_projects                             NUMBER(1),
    round2_pending_resume                       NUMBER(1),
    round2_other_technologies                   NUMBER(1),
    round2_good_attitude                        NUMBER(1),
    round2_confidence                           NUMBER(1),
    recommendation                              VARCHAR2(40) NOT NULL,
    comments                                    VARCHAR2(4000),
    created_at                                  TIMESTAMP DEFAULT SYSTIMESTAMP
)
"""


def _table_exists(cur) -> bool:
    """Check the data dictionary instead of firing CREATE TABLE and hoping
    for ORA-00955. ALL_TABLES is readable by any user, unlike the hidden
    identity sequence Oracle touches during CREATE TABLE — so this avoids
    ever attempting DDL against a table this user doesn't own, which is
    what was raising ORA-41900 (missing READ on the ISEQ$$_... sequence)
    and leaking an orphaned sequence in CHAKORA on every failed attempt."""
    cur.execute(
        "SELECT COUNT(*) FROM all_tables WHERE owner = 'CHAKORA' "
        "AND table_name = 'INTERVIEW_FEEDBACK'"
    )
    return cur.fetchone()[0] > 0


def init_db(seed_if_empty: bool = False):
    print("[interview_service] using existing 'interview_feedback' table")

# ------------------------------------------------------------------
# SCORE FIELDS  (per-round scorecards — matches interview_submit.html)
# ------------------------------------------------------------------
ROUND1_FIELDS = [
    "round1_communication_soft_skills",
    "round1_basic_technical_skill_assessment",
    "round1_project_explanation",
    "round1_logical_ability",
    "round1_resume",
]
ROUND1_LABELS = {
    "round1_communication_soft_skills": "Communication & Soft skills",
    "round1_basic_technical_skill_assessment": "Basic Technical/Skill Assessment",
    "round1_project_explanation": "Project explanation",
    "round1_logical_ability": "Logical Ability",
    "round1_resume": "Resume",
}

ROUND2_FIELDS = [
    "round2_introduction",
    "round2_general_programming",
    "round2_python_basics",
    "round2_python_advanced",
    "round2_oops",
    "round2_projects",
    "round2_pending_resume",
    "round2_other_technologies",
    "round2_good_attitude",
    "round2_confidence",
]
ROUND2_LABELS = {
    "round2_introduction": "Introduction",
    "round2_general_programming": "General programming",
    "round2_python_basics": "Python basics",
    "round2_python_advanced": "Python advanced",
    "round2_oops": "OOPS",
    "round2_projects": "Projects",
    "round2_pending_resume": "Pending resume",
    "round2_other_technologies": "Other technologies",
    "round2_good_attitude": "Good attitude",
    "round2_confidence": "Confidence",
}

ALL_SCORE_FIELDS = ROUND1_FIELDS + ROUND2_FIELDS

REC_TO_SCORE = {"Strong Hire": 4, "Hire": 3, "No Hire": 2, "Strong No Hire": 1}
SCORE_TO_REC = {v: k for k, v in REC_TO_SCORE.items()}
POSITIVE_RECS = {"Hire", "Strong Hire"}
NEGATIVE_RECS = {"No Hire", "Strong No Hire"}


def _final_recommendation(recs):
    has_positive = any(r in POSITIVE_RECS for r in recs)
    has_negative = any(r in NEGATIVE_RECS for r in recs)
    if has_positive and has_negative:
        return "Split Decision - Needs Discussion"
    avg = statistics.mean(REC_TO_SCORE[r] for r in recs)
    rounded = min(max(round(avg), 1), 4)
    return SCORE_TO_REC[rounded]


def _scored_fields(row):
    """Which scorecard (round1 or round2) this row was actually filled in with.
    The submit form only enables/POSTs one set at a time, so a row will have
    real values for exactly one set and NULLs for the other."""
    if any(row.get(f) is not None for f in ROUND1_FIELDS):
        return ROUND1_FIELDS, ROUND1_LABELS
    return ROUND2_FIELDS, ROUND2_LABELS


def consolidate(rows):
    by_candidate = defaultdict(list)
    for row in rows:
        by_candidate[row["candidate_name"]].append(row)

    results = []
    for candidate, entries in by_candidate.items():
        position = entries[-1]["position"]

        dim_values = defaultdict(list)   # label -> [scores...] across whichever entries used that dimension
        entry_avgs = []                  # one overall average per entry (round), for the candidate's overall score

        for e in entries:
            fields, labels = _scored_fields(e)
            vals = [e[f] for f in fields if e.get(f) is not None]
            if not vals:
                continue
            entry_avgs.append(statistics.mean(vals))
            for f in fields:
                if e.get(f) is not None:
                    dim_values[labels[f]].append(e[f])

        dim_avgs = {label: round(statistics.mean(vals), 2) for label, vals in dim_values.items()}
        overall_avg = round(statistics.mean(entry_avgs), 2) if entry_avgs else 0.0
        recs = [e["recommendation"] for e in entries]
        final_rec = _final_recommendation(recs)

        results.append({
            "candidate": candidate,
            "position": position,
            "rounds_completed": len(entries),
            "dimension_averages": dim_avgs,
            "overall_average": overall_avg,
            "final_recommendation": final_rec,
        })

    results.sort(key=lambda r: r["overall_average"], reverse=True)
    return results


# ------------------------------------------------------------------
# DATA ACCESS
# ------------------------------------------------------------------
def _row_to_dict(cursor, row):
    columns = [d[0].lower() for d in cursor.description]
    return dict(zip(columns, row))


def get_all_feedback():
    conn = get_connection()
    try:
        cur = conn.cursor()
        cur.execute("SELECT * FROM SYS.INTERVIEW_FEEDBACK ORDER BY interview_date ASC, id ASC")
        return [_row_to_dict(cur, r) for r in cur.fetchall()]
    finally:
        conn.close()


def get_candidate_feedback(candidate_name: str):
    conn = get_connection()
    try:
        cur = conn.cursor()
        cur.execute(
            "SELECT * FROM SYS.INTERVIEW_FEEDBACK WHERE candidate_name = :1 ORDER BY interview_date ASC, id ASC",
            [candidate_name],
        )
        return [_row_to_dict(cur, r) for r in cur.fetchall()]
    finally:
        conn.close()


def get_feedback_by_id(feedback_id: int):
    conn = get_connection()
    try:
        cur = conn.cursor()
        cur.execute("SELECT * FROM SYS.INTERVIEW_FEEDBACK WHERE id = :1", [feedback_id])
        row = cur.fetchone()
        return _row_to_dict(cur, row) if row else None
    finally:
        conn.close()


_INSERT_SQL = """INSERT INTO SYS.INTERVIEW_FEEDBACK
    (candidate_name, position, interview_round, interviewer_name, interview_date,
     round1_communication_soft_skills, round1_basic_technical_skill_assessment,
     round1_project_explanation, round1_logical_ability, round1_resume,
     round2_introduction, round2_general_programming, round2_python_basics,
     round2_python_advanced, round2_oops, round2_projects, round2_pending_resume,
     round2_other_technologies, round2_good_attitude, round2_confidence,
     recommendation, comments)
    VALUES
    (:candidate_name, :position, :interview_round, :interviewer_name, :interview_date,
     :round1_communication_soft_skills, :round1_basic_technical_skill_assessment,
     :round1_project_explanation, :round1_logical_ability, :round1_resume,
     :round2_introduction, :round2_general_programming, :round2_python_basics,
     :round2_python_advanced, :round2_oops, :round2_projects, :round2_pending_resume,
     :round2_other_technologies, :round2_good_attitude, :round2_confidence,
     :recommendation, :comments)"""

_UPDATE_SQL = """UPDATE SYS.INTERVIEW_FEEDBACK SET
        candidate_name = :candidate_name,
        position = :position,
        interview_round = :interview_round,
        interviewer_name = :interviewer_name,
        interview_date = :interview_date,
        round1_communication_soft_skills = :round1_communication_soft_skills,
        round1_basic_technical_skill_assessment = :round1_basic_technical_skill_assessment,
        round1_project_explanation = :round1_project_explanation,
        round1_logical_ability = :round1_logical_ability,
        round1_resume = :round1_resume,
        round2_introduction = :round2_introduction,
        round2_general_programming = :round2_general_programming,
        round2_python_basics = :round2_python_basics,
        round2_python_advanced = :round2_python_advanced,
        round2_oops = :round2_oops,
        round2_projects = :round2_projects,
        round2_pending_resume = :round2_pending_resume,
        round2_other_technologies = :round2_other_technologies,
        round2_good_attitude = :round2_good_attitude,
        round2_confidence = :round2_confidence,
        recommendation = :recommendation,
        comments = :comments
    WHERE id = :id"""


def insert_feedback(data: dict):
    conn = get_connection()
    try:
        cur = conn.cursor()
        cur.execute(_INSERT_SQL, data)
        conn.commit()
    finally:
        conn.close()


def update_feedback(feedback_id: int, data: dict):
    conn = get_connection()
    try:
        cur = conn.cursor()
        cur.execute(_UPDATE_SQL, {**data, "id": feedback_id})
        conn.commit()
    finally:
        conn.close()


def delete_candidate(candidate_name: str):
    conn = get_connection()
    try:
        cur = conn.cursor()
        cur.execute("DELETE FROM SYS.INTERVIEW_FEEDBACK WHERE candidate_name = :1", [candidate_name])
        conn.commit()
    finally:
        conn.close()


def delete_feedback_entry(feedback_id: int):
    conn = get_connection()
    try:
        cur = conn.cursor()
        cur.execute("DELETE FROM SYS.INTERVIEW_FEEDBACK WHERE id = :1", [feedback_id])
        conn.commit()
    finally:
        conn.close()


# ------------------------------------------------------------------
# FASTAPI APP
# ------------------------------------------------------------------
@asynccontextmanager
async def lifespan(app: FastAPI):
    init_db(seed_if_empty=False)
    yield


app = FastAPI(title="Interview Feedback Microservice", lifespan=lifespan)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten this to the Flask front end's origin in production
    allow_methods=["*"],
    allow_headers=["*"],
)


class FeedbackIn(BaseModel):
    candidate_name: str
    position: str
    interview_round: str
    interviewer_name: str
    interview_date: str

    round1_communication_soft_skills: Optional[int] = None
    round1_basic_technical_skill_assessment: Optional[int] = None
    round1_project_explanation: Optional[int] = None
    round1_logical_ability: Optional[int] = None
    round1_resume: Optional[int] = None

    round2_introduction: Optional[int] = None
    round2_general_programming: Optional[int] = None
    round2_python_basics: Optional[int] = None
    round2_python_advanced: Optional[int] = None
    round2_oops: Optional[int] = None
    round2_projects: Optional[int] = None
    round2_pending_resume: Optional[int] = None
    round2_other_technologies: Optional[int] = None
    round2_good_attitude: Optional[int] = None
    round2_confidence: Optional[int] = None

    recommendation: str
    comments: str = ""


@app.get("/health")
def health():
    return {"service": "interview_service", "status": "healthy"}


@app.get("/api/interview/feedback")
def api_all_feedback():
    """Every raw row + the per-candidate consolidated view (dashboard needs both)."""
    rows = get_all_feedback()
    return {
        "rows": rows,
        "candidates": consolidate(rows) if rows else [],
        "total_submissions": len(rows),
    }


@app.get("/api/interview/candidate/{candidate_name}")
def api_candidate_detail(candidate_name: str):
    rows = get_candidate_feedback(candidate_name)
    if not rows:
        raise HTTPException(status_code=404, detail="Candidate not found")
    summary = consolidate(rows)[0]
    return {"candidate": summary, "rounds": rows}


@app.post("/api/interview/feedback", status_code=201)
def api_submit_feedback(payload: FeedbackIn):
    data = payload.model_dump()
    data["candidate_name"] = data["candidate_name"].strip()
    data["comments"] = data["comments"].strip()
    insert_feedback(data)
    return {"candidate_name": data["candidate_name"]}


@app.get("/api/interview/feedback/{feedback_id}")
def api_get_feedback(feedback_id: int):
    entry = get_feedback_by_id(feedback_id)
    if not entry:
        raise HTTPException(status_code=404, detail="Feedback entry not found")
    return entry


@app.put("/api/interview/feedback/{feedback_id}")
def api_update_feedback(feedback_id: int, payload: FeedbackIn):
    if not get_feedback_by_id(feedback_id):
        raise HTTPException(status_code=404, detail="Feedback entry not found")
    data = payload.model_dump()
    data["candidate_name"] = data["candidate_name"].strip()
    data["comments"] = data["comments"].strip()
    update_feedback(feedback_id, data)
    return {"candidate_name": data["candidate_name"]}


@app.delete("/api/interview/feedback/{feedback_id}")
def api_delete_feedback(feedback_id: int):
    entry = get_feedback_by_id(feedback_id)
    if not entry:
        raise HTTPException(status_code=404, detail="Feedback entry not found")
    delete_feedback_entry(feedback_id)
    remaining = get_candidate_feedback(entry["candidate_name"])
    return {"candidate_name": entry["candidate_name"], "candidate_has_remaining_rounds": bool(remaining)}


@app.delete("/api/interview/candidate/{candidate_name}")
def api_delete_candidate(candidate_name: str):
    delete_candidate(candidate_name)
    return {"status": "deleted", "candidate_name": candidate_name}


if __name__ == "__main__":
    import uvicorn
    print("[interview_service] starting FastAPI app on port 8003")
    uvicorn.run("interview_service:app", host="0.0.0.0", port=8003, reload=True)